import { Poppins } from "next/font/google";
import "./globals.css";
import Header from "@/app/components/Header";

const poppins = Poppins({
    weight:['400','700'],
    subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={poppins.className}>
      <Header />
      <div className='container'>{children}</div>
      </body>
    </html>
  )
}

export default RootLayout